### ISSUE TITLE
Synfeld test errors

### ISSUE THREAD

**Issue by megatux** [jeremyevans/r10k#6]
Looks like Synfield tests don't work for me, synfeld version (0.0.6)

`
/home/megatux/.asdf/installs/ruby/2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rack/mount (LoadError)
	from /home/megatux/.asdf/installs/ruby/2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/megatux/.asdf/installs/ruby/2.4.6/lib/ruby/gems/2.4.0/gems/synfeld-0.0.6/lib/synfeld.rb:7:in `<top (required)>'
`

**Comment by jeremyevans** [comment]
Can you try synfeld 0.0.7?  Honestly, we may want to turn it off by default, it is super slow for large numbers of routes and was never popular.

**Comment by megatux** [comment]
Ok, tried `bundle update synfeld` but didn't work, some _rack_ conflict, so did an "update" of everything, but it downgraded rack, rails, cuba, sinatra, etc, so it's a dependency hell here :/

**Comment by megatux** [comment]
```
$ bundle update synfeld
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 2.0.7)

  In Gemfile:
    cuba was resolved to 3.9.2, which depends on
      rack (>= 1.6.0)

    synfeld (~> 0.0.7) was resolved to 0.0.7, which depends on
      rack (~> 1.4.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.




$ bundle update 
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.............................................................................................................................................................................................................................................................................................................................................................................................
Using rake 13.0.0
Fetching activesupport 2.3.2 (was 5.2.3)
Installing activesupport 2.3.2 (was 5.2.3)
Fetching actionpack 2.3.2 (was 5.2.3)
Installing actionpack 2.3.2 (was 5.2.3)
Fetching actionmailer 2.3.2 (was 5.2.3)
Installing actionmailer 2.3.2 (was 5.2.3)
Fetching activerecord 2.3.2 (was 5.2.3)
Installing activerecord 2.3.2 (was 5.2.3)
Fetching activeresource 2.3.2
Installing activeresource 2.3.2
Using bundler 2.0.2
Fetching rack 1.4.7 (was 2.0.7)
Installing rack 1.4.7 (was 2.0.7)
Fetching cuba 3.4.0 (was 3.9.2)
Installing cuba 3.4.0 (was 3.9.2)
Using rmagick 2.16.0
Using gruff 0.7.0
Fetching haml 3.1.8
Installing haml 3.1.8
Fetching hanami 0.0.0 (was 1.3.3)
Installing hanami 0.0.0 (was 1.3.3)
Using tilt 2.0.10
Using nyny 2.2.1
Using rack-app 7.5.2
Fetching rack-mount 0.8.3
Installing rack-mount 0.8.3
Fetching rack-protection 1.5.5 (was 2.0.7)
Installing rack-protection 1.5.5 (was 2.0.7)
Fetching rails 2.3.2 (was 5.2.3)
Installing rails 2.3.2 (was 5.2.3)
Using roda 3.24.0
Using seg 1.2.0
Fetching sinatra 1.4.6 (was 2.0.7)
Installing sinatra 1.4.6 (was 2.0.7)
Fetching synfeld 0.0.7 (was 0.0.6)
Installing synfeld 0.0.7 (was 0.0.6)
Fetching syro 0.0.4 (was 3.1.1)
Installing syro 0.0.4 (was 3.1.1)
Bundle updated!
```

**Comment by megatux** [comment]
Agree, Synfeld needs an upgrade or it will conflict with others.

**Comment by jeremyevans** [comment]
The real issue is trying to use one Gemfile.  Bundler thinks all gems listed need to work together, when in actuality all frameworks are tested in separate processes and don't need to work together.  It would probably be best to just remove the Gemfile.

**Comment by jeremyevans** [comment]
I've removed the Gemfile and added instructions to the README for installing the gems.
